# Generated by Django 4.0.1 on 2022-02-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
